[YOLOv8] Onnx Export Support
neuralmagic/sparseml pull request #1373
Opened 2023-02-09 11:53 UTC by dbogunowicz

2023-02-09 18:49 UTC, corey-nm requested changes
Looks great!

1. Can you test exporting with a yolov8 checkpoint if you haven't already?
2. Can you add a section to the README with instructions? PR description looks great so can probably just copy that

2023-02-10 18:03 UTC, bfineran approved these changes
LGTM - echoing corey would also add an example of the expected output directory structure to pr desc/docs

2023-02-10 18:03 UTC, bfineran commented on src/sparseml/pytorch/utils/exporter.py
> +        :param onnx_model_name: name of the onnx model file. Default is None
```suggestion
        :param onnx_model_name: name of the onnx model file. Defaults to `model.onnx`
```

2023-02-13 13:26 UTC, dbogunowicz commented on src/sparseml/pytorch/yolov8/README.md
> +
```suggestion
```

2023-02-13 13:31 UTC, bfineran approved these changes

2023-02-13 15:55 UTC, merged