[WIP] PyTorch Global Magnitude Pruning
neuralmagic/sparseml pull request #142
Opened 2021-04-03 02:40 UTC by bfineran

* [x] refactor mask creators and masking objects to process lists of tensors instead of single tensors
* [ ] implement global magnitude mask creator
* [ ] testing

2021-04-06 19:50 UTC, bfineran commented
Current status is this PR will be on hold until other algorithms are landed on main

2021-04-08 15:01 UTC, bfineran commented
Putting this back up for review

2021-04-08 17:40 UTC, kevinaer submitted a review, later dismissed

2021-04-09 12:58 UTC, markurtz submitted a review, later dismissed

2021-04-09 13:02 UTC, markurtz commented
Overall looks good, 2 notes for the future to keep an eye on:

- I'm worried about the memory hit we're going to take on creating a new tensor the size of all the params that are used to just calculate the threshold. This may be something we need to do on the CPU, or at least have an option for, instead of keeping the tensor on the current device
- Also worried about the discoverability of global magnitude. As we're doing the refactor and renaming, it may make sense to break out GradualMagnitude and GlobalMagnitude into their own root level classes that extend the same base class so it's more discoverable and readily available in docs and tutorials

2021-04-09 14:46 UTC, natuan submitted a review, later dismissed
LGTM. For future iteration, I wonder if the `create_sparsity_masks` could be simplified by always create mask with the defined sparsity on top of all tensors passed in. The distinction between global and layer-wise would be made from the call-sites by either passing a tensor list, or calling this func on separate tensors (there's a burden for layer wise here, but might worth it to simplify the create mask code)

2021-04-09 17:51 UTC, bfineran commented
@markurtz updated to include child classes for pruning modifiers, note that we will have to be careful about `ModifierProp` serialization when inheriting from a class with more props.  Agreed on the memory issue, definitely something to keep an eye out for.

@natuan That implementation would move logic for when to group globally or not to two different places (the call site would have to pass in tensors separately), as implemented, the only place in the stack that cares about global or not, other than propagating, is the mask creator.  I do think adding support for a single tensor input would be good though.

2021-04-09 20:17 UTC, markurtz submitted a review, later dismissed

2021-04-09 20:27 UTC, kevinaer requested changes

2021-04-09 20:27 UTC, kevinaer commented on tests/sparseml/pytorch/optim/test_modifier_pruning.py
> +)
Can you remove the skips? I am not sure if it is being used in some legacy job but environment based skipping is no longer being used in favor of make targets.

2021-04-09 20:27 UTC, kevinaer commented on tests/sparseml/pytorch/optim/test_modifier_pruning.py
> +)
Can you remove the skips? I am not sure if it is being used in some legacy job but environment based skipping is no longer being used in favor of make targets.

2021-04-09 22:00 UTC, bfineran commented
@kevinaer resolved, thanks!

2021-04-09 22:26 UTC, kevinaer approved these changes

2021-04-09 22:31 UTC, markurtz approved these changes

2021-04-09 22:45 UTC, merged