sparse BERT + Distilation
neuralmagic/sparseml pull request #150
Opened 2021-04-05 18:58 UTC by spacemanidol

2021-04-05 19:14 UTC, spacemanidol commented
base code is up. Working on cleaning up the scripts for public usage and improved integration with huggingface

2021-04-05 20:26 UTC, spacemanidol commented
Code cleaned up for public usage. Awaiting results of distillation with pruning and layer dropping. All other components are ready for review @bfineran @markurtz.

2021-04-15 13:10 UTC, jeanniefinks requested changes
This file needs several editorial updates.
e.g., demostrate or absed or Distilation

Consider taking another pass through it and happy to be added as a reviewer!

2021-04-15 17:48 UTC, spacemanidol commented
@jeanniefinks please go ahead and call our any changes required. At this point, I am just awaiting results on experiments.

2021-04-19 15:11 UTC, markurtz submitted a review, later dismissed

2021-04-19 15:23 UTC, bfineran requested changes
LGTM outside of nits and the extra wandb line. Would it be possible in the future to compress the recipes to just use a single `GMPruningModifier` if the params are the same across all layers?

2021-04-19 15:23 UTC, bfineran commented on integrations/transformers/run_qa.py
> +    wandb.init(project='BERT-QA-SPARSEML', entity='spacemanidol') # REMOVE before pushing code
make sure to remove

2021-04-19 15:23 UTC, bfineran commented on integrations/transformers/run_qa.py
> +    print(training_args.num_train_epochs)
nit: can we use the `logger` here?

2021-04-19 15:23 UTC, bfineran commented on integrations/transformers/run_qa.py
> +    print(training_args.num_train_epochs)
nit: can we use the logger here?

2021-04-19 16:35 UTC, spacemanidol commented on integrations/transformers/run_qa.py
> +    print(training_args.num_train_epochs)
these are unneeded so I dropped them

2021-04-19 16:35 UTC, spacemanidol commented on integrations/transformers/run_qa.py
> +    print(training_args.num_train_epochs)
unneeded so removed

2021-04-19 16:35 UTC, spacemanidol commented on integrations/transformers/run_qa.py
> +    wandb.init(project='BERT-QA-SPARSEML', entity='spacemanidol') # REMOVE before pushing code
wandb gone.

2021-04-21 15:28 UTC, bfineran approved these changes, later dismissed

2021-04-22 18:28 UTC, markurtz approved these changes

2021-04-22 18:28 UTC, merged