[YOLOv8] Fix support for `--dataset_dir` argument
neuralmagic/sparseml pull request #1520
Opened 2023-04-13 13:57 UTC by dbogunowicz

This PR: #1513 was not tested rigorously and was failing for all the pathways. This PR fixes this.

Testing:
- tested validation pathway
- tested export pathway (generating samples and using the data for calculating gradients at one-shot)
- tested training pathway

2023-04-13 18:08 UTC, anmarques requested changes
Looks good to me. I just recommend replacing --datasets-dir by --dataset-path where the later refers to the complete path to the dataset rather than it's parent directory

2023-04-13 18:08 UTC, anmarques commented on src/sparseml/yolov8/val.py
> +    default="/home/ubuntu/damian/sparseml/funny_dir",
Maybe leave default as None 😄

2023-04-13 19:48 UTC, bfineran submitted a review, later dismissed

2023-04-13 19:48 UTC, bfineran commented
LGTM pending comment

2023-04-14 11:39 UTC, dbogunowicz commented on src/sparseml/yolov8/val.py
> +    default="/home/ubuntu/damian/sparseml/funny_dir",
```suggestion
    default=None,
```

2023-04-14 14:16 UTC, anmarques requested changes

2023-04-14 14:16 UTC, anmarques commented on src/sparseml/yolov8/export.py
> +    "--dataset_path",
Let's use --dataset-path, making it consistent w/ other arguments (dash instead of underscore)

2023-04-14 14:16 UTC, anmarques commented on src/sparseml/yolov8/train.py
> +    "--dataset_path",
Let's use --dataset-path, making it consistent w/ other arguments (dash instead of underscore)

2023-04-14 14:16 UTC, anmarques commented on src/sparseml/yolov8/utils/helpers.py
> +    if os.path.basename(dataset_path) != os.path.splitext(data)[0]:
We don't have to impose this constraint. For instance, I doing something like ~/datasets/my_coco should still be acceptable with coco.yaml.

The dataset path doesn't have to be related to the name of the dataset

2023-04-14 14:16 UTC, anmarques commented on src/sparseml/yolov8/val.py
> +    "--dataset_path",
Let's use --dataset-path, making it consistent w/ other arguments (dash instead of underscore)

2023-04-14 15:10 UTC, dbogunowicz commented on src/sparseml/yolov8/train.py
> +    "--dataset_path",
```suggestion
    "--dataset-path",
```

2023-04-14 15:11 UTC, dbogunowicz commented on src/sparseml/yolov8/export.py
> +    "--dataset_path",
```suggestion
    "--dataset-path",
```

2023-04-14 19:37 UTC, anmarques approved these changes

2023-04-20 10:29 UTC, rahul-tuli approved these changes

2023-04-20 10:29 UTC, rahul-tuli commented on src/sparseml/yolov8/utils/helpers.py
> +        (saved in the current working directory)
Is there an extra space here?

2023-04-20 10:55 UTC, merged