Ultralytics direct integration documentation
neuralmagic/sparseml pull request #162
Opened 2021-04-07 20:15 UTC by bfineran

2021-04-09 13:03 UTC, markurtz requested changes
I haven't looked through the docs yet, will do a bit later today. But, we do need to put a new section in the index.rst for Integrations and have this as one of the links under it

2021-04-14 17:15 UTC, markurtz commented on docs/integrations/ultralytics.md
> +have to be set.  In generall, all should be set when running with SparseML
typo: generall

2021-04-14 22:02 UTC, bfineran commented
@markurtz added a section in `index.rst` for integrations. let me know if this works/is what you had in mind

2021-04-14 22:05 UTC, markurtz submitted a review, later dismissed

2021-04-14 23:37 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +### Other arguments
```suggestion
### Other Arguments
```

2021-04-14 23:38 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +* `--use-leaky-relu` - LeakyReLU runs best on the DeepSparse engine. Setting this flag
```suggestion
* `--use-leaky-relu` - LeakyReLU runs best on the DeepSparse Engine. Setting this flag
```

2021-04-14 23:38 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +After downloading, the weights can be moved to a file locatin of your choice:
```suggestion
After downloading, the weights can be moved to a file location of your choice:
```

2021-04-14 23:39 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +### Example command
```suggestion
### Example Command
```

2021-04-14 23:39 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +engine, take a look at the `deepsparse/` examples
```suggestion
Engine, take a look at the `deepsparse/` examples
```

2021-04-14 23:41 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +    for inference with the [DeepSparse](https://github.com/neuralmagic/deepsparse)
```suggestion
    for inference with the [DeepSparse Engine](https://github.com/neuralmagic/deepsparse)
```

2021-04-14 23:41 UTC, jeanniefinks commented on docs/integrations/ultralytics.md
> +    engine
```suggestion

```

2021-04-22 18:30 UTC, markurtz approved these changes

2021-07-13 13:54 UTC, bfineran commented
closing since the integration has now moved to a public fork of the `yolov3` repo and our integrations structure has changed.

2021-07-13 13:54 UTC, closed without merging