Set lower validation batch size for yolov8
neuralmagic/sparseml pull request #1629
Opened 2023-06-15 22:39 UTC by abhinavnmagic

Ultralytics by default sets the validation batch size as twice the training batch size. This leads to OOM with our integration for YoloV8 m,l and x models.

The fix is to set the validation batch size to be one-fourth of the training batch size.
I tested the changes while training yolov8 models.

2023-06-16 00:50 UTC, anmarques approved these changes

2023-06-16 00:51 UTC, anmarques requested changes

2023-06-16 00:51 UTC, anmarques commented on src/sparseml/yolov8/trainers.py
> +            self.test_loader = self.get_dataloader(self.testset, batch_size=max(1, self.train_loader.batch_size // 4), rank=-1, mode='val')
Won't this lead to batch size 0 if the original batch size is between 1 and 3? Maybe make sure that it's at least 1

2023-06-16 02:24 UTC, bfineran approved these changes

2023-06-20 18:36 UTC, bfineran approved these changes

2023-06-20 18:39 UTC, merged