Onnx framework and sparsification implementation for phase 2
neuralmagic/sparseml pull request #171
Opened 2021-04-11 19:14 UTC by markurtz

ONNX functionality for phase2 to enable loading the information available for training, sparsifying, and exporting for within the ONNX framework

2021-04-12 15:24 UTC, kevinaer requested changes

2021-04-12 15:24 UTC, kevinaer commented on src/sparseml/onnx/framework/info.py
> +        all_providers = get_all_providers
Should be `all_providers = get_all_providers()`

2021-04-20 14:02 UTC, kevinaer approved these changes, later dismissed

2021-04-22 19:12 UTC, natuan submitted a review, later dismissed

2021-04-23 21:34 UTC, mgoin approved these changes, later dismissed

2021-04-26 18:11 UTC, merged