Pytorch OBCQ Implementation
neuralmagic/sparseml pull request #1714
Opened 2023-09-05 19:02 UTC by Satrat

### How to Run
An example recipe file is located at `src/sparseml/pytorch/sparsification/obcq/example.yaml`
```
python src/sparseml/pytorch/sparsification/obcq/obcq.py facebook/opt-350m c4 --recipe src/sparseml/pytorch/sparsification/obcq/example.yaml 
```

2023-09-06 20:04 UTC, bfineran requested changes
LGTM overall - since this runs in one shot and doesn't follow the normal training lifecycle the other pytorch based modifiers do, the main missing piece is serialization.  The code/names look a bit more on the research side (ie mixed case, abbreviations, generic names, etc) and some doc strings are missing.

2023-09-06 20:04 UTC, bfineran commented on src/sparseml/transformers/sparsification/obcq/sparse_gpt_modifier.py
> +        sequential_update: Optional[bool] = True,
for serialization, need to mark these as `@ModifierProp`s (see other modifiers for example). also good to add a serialization test (see other modifiers for example)

2023-09-06 20:04 UTC, bfineran commented on src/sparseml/transformers/sparsification/obcq/sparse_gpt_modifier.py
> +    def one_shot(self, model, dataloader, initializer_kwargs, finalize_kwargs):
would be great to move all this functionality into just initialize and finalize, so at the generic modifier/manager level, one shot can be applied by just calling these two

2023-09-07 20:52 UTC, Satrat commented on src/sparseml/transformers/sparsification/obcq/layer_compressor.py
> +            self.layer(self.inputs[j].unsqueeze(0), attention_mask=attn_mask)[0]
I'm not sure actually, I pulled this line from Tuan's code so let me check with him

2023-10-19 19:56 UTC, closed without merging