Update transformers/__init__.py to warn about nm_transformers
neuralmagic/sparseml pull request #1730
Opened 2023-09-21 20:31 UTC by mgoin

This would fail if the attribute wasn't present rather than warn

```
  File "sparseml/src/sparseml/transformers/__init__.py", line 43, in _check_transformers_install
    if not _transformers.NM_INTEGRATED:
  File "lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1177, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute NM_INTEGRATED
```

2023-09-21 20:38 UTC, dbarbuzzi commented on src/sparseml/transformers/__init__.py
> +            "installed via `pip install nm_transformers`"
nit: the PyPI package name is `nm-transformers` (hyphen, not underscore). Using an underscore instead will work with `pip install` though I think matching the name more accurately is better for consistency/etc.

2023-09-21 20:41 UTC, bfineran requested changes
Should raise a bit louder of a warning here since this would mean that the quantized matmuls would not be applied which is a significant difference for sparseml flows

2023-09-22 07:51 UTC, dbogunowicz approved these changes
Can we have the same diff for deepsparse?

2023-09-22 17:00 UTC, mgoin commented
> Can we have the same diff for deepsparse?

Deepsparse already has a fix to properly access the attribute and I think the critical-ness of using nm-transformers with deepsparse is much less than sparseml. Happy to escalate deepsparse's warning if y'all think it's warranted

2023-10-05 20:08 UTC, merged