Fix typo
neuralmagic/sparseml pull request #184
Opened 2021-04-20 22:47 UTC by eldarkurtic

2021-04-20 23:17 UTC, bfineran requested changes
thanks for the catch @eldarkurtic. Left an additional change

2021-04-20 23:17 UTC, bfineran commented on src/sparseml/pytorch/optim/modifier_pruning.py
>                  ).format(self._init_sparsity, self.__class__.__name__)
```suggestion
                ).format(self._final_sparsity, self.__class__.__name__)
```

2021-04-20 23:18 UTC, bfineran approved these changes

2021-04-21 17:56 UTC, markurtz approved these changes

2021-04-21 19:18 UTC, merged