[Fix]"ValueError: scheme_overrides contains submodule names or module types that do not match to any submodules in the model" when using mpt model in sparseml.transformers.export_onnx
neuralmagic/sparseml pull request #1846
Opened 2023-11-21 11:09 UTC by dbogunowicz

Fix for: https://app.asana.com/0/1205724081986514/1205917069172910

The possible solution was either to catch the error or set --trust_remote_code flag True by default. I like the first solution much better. It is verbose, indicates where the error has occurred, and most importantly, does not work against the user's assumptions (HF has gotten us used to having this flag set to False by default).

When I get the buy-in from the stakeholders, I will also cherry-pick this to 1.6.

2023-11-21 12:12 UTC, derekk-nm requested changes

2023-11-21 12:12 UTC, derekk-nm commented on src/sparseml/transformers/export.py
> +            f"Failed to applied the recipy to the "
minor typo, recipy = recipe

2023-11-21 15:10 UTC, dbogunowicz commented on src/sparseml/transformers/export.py
> +            f"Failed to applied the recipy to the "
```suggestion
            f"Failed to apply the recipe to the "
```

2023-11-22 13:03 UTC, bfineran approved these changes

2023-11-22 15:20 UTC, merged