[Export Refactor] Feature Branch
neuralmagic/sparseml pull request #1858
Opened 2023-11-28 15:34 UTC by dbogunowicz

## Feature Description

Feature branch that implements new exporting framework. This PR roughly outlines the new design as outlined in the diagram below:
<img width="1131" alt="image" src="https://github.com/neuralmagic/sparseml/assets/97082108/c99b1357-3702-4f80-9e8b-f5df78eabc2c">
## Features

The first order of business is to migrate Image Classification export to use the new framework. The related PRs are:
- [x] #1878 
- [x] #1880
- [x] #1883 
- [x] #1884 
- [x] #1888 
- [x] #1889 
- [x] #1890
- [x] Test the new Image Classification export end to end (#1898)

The second work item is to implement Transformers export:
- [x] #1908 
- [x] #1909 
- [x] #1910 

After the aforementioned smaller PRs land, the next order of affairs would be to:
- [ ] Add some basic documentation
- [ ] Remove the part of the codebase responsible for legacy export and swap the outward-facing pathways to use the new export
- [x] Fix any pending tests

Also add few missing, potentially slightly orthogonal features:
- [x] Make sure that all `create_model` functions properly create sparse models (use @Satrat 's new modifiers), also apply one shot etc.
- [ ] Validate `validate_correctness` function (some sparsezoo edits are required)
- [ ] Properly implement and validate separating the exported onnx model into multiple files
- [x] Use `device` argument when creating a model
- [ ] (Potentially) set `is_tar` as an export argument (to decide later)

**CLI Example**
```bash
sparseml.export PATH/TO/SPARSIFIED/LLM \
  --task text-generation
```

2023-11-29 15:46 UTC, bfineran commented on src/sparseml/export.py
> +class SparseMLIntegrationRegistry(RegistryMixin):
note - we can use mixin directly on the registered class if we want to (as an additional parent class)

2024-01-02 14:53 UTC, Satrat requested changes

2024-01-02 14:53 UTC, Satrat commented on src/sparseml/transformers/sparsification/obcq/obcq.py
> +        recipe=recipe_file,
I think this is the reason for the failing tests. We're initializing the model with the recipe we want to apply to it, but it should be initialized with `input_recipe_path` instead, defined on deleted lines 130-137. `recipe_file` shouldn't get applied to the model until we call the `apply` function

2024-01-02 18:45 UTC, Satrat reviewed
Latest commits LGTM, just had some small comments. Lets also be sure to test this on llama 7b before landing to make sure we're getting the same perplexity results as before

2024-01-02 18:45 UTC, Satrat commented on src/sparseml/export/export.py
> +    device: str = "cpu",
Why do we change this default from auto to cpu? on line 118 it looks like we're expecting auto as a default

2024-01-02 18:45 UTC, Satrat commented on src/sparseml/transformers/utils/initializers.py
> +    _LOGGER.info(
Could we add another log statement on success that prints out the path to the recipe we are loading?

2024-01-10 19:47 UTC, Satrat approved these changes

2024-01-10 19:48 UTC, Satrat submitted a review, later dismissed
LGTM, just have one unresolved comment about adding an additional log message. Also looks like we need to resolve a merge conflict with the GHA file

2024-01-10 21:33 UTC, bfineran approved these changes

2024-01-10 21:33 UTC, merged