[Logger Refactor] Add timer in logger manager
neuralmagic/sparseml pull request #1967
Opened 2024-01-17 13:53 UTC by rahul-tuli

This PR adds a time context manager to LoggerManager's `SystemLoggingWraper`

```python
from time import sleep
from sparseml.core import LoggerManager
from logging import INFO
logger_manager = LoggerManager()

with logger_manager.system.time('test', level=INFO):
    sleep(1)
```

Output:
```bash
Logging all SparseML modifier-level logs to sparse_logs/17-01-2024_08.49.07.log
2024-01-17 08:49:07 sparseml.core.logger.logger INFO     Logging all SparseML modifier-level logs to sparse_logs/17-01-2024_08.49.07.log
manager test: 1.000s

```

2024-01-17 17:19 UTC, Satrat approved these changes
nice and clean!

2024-01-17 20:19 UTC, bfineran requested changes

2024-01-17 20:19 UTC, bfineran commented on src/sparseml/core/logger/logger.py
> +        self.log_string(tag=tag, string=f"{elapsed:.3f}s", *args, **kwargs)
We should be logging a float not a string, will allow for easier plotting and such

2024-01-18 10:26 UTC, dbogunowicz approved these changes

2024-01-19 19:21 UTC, merged