Update annotate.py
neuralmagic/sparseml pull request #199
Opened 2021-04-27 20:31 UTC by jeanniefinks

minor edits, thx

2021-04-27 20:33 UTC, bfineran requested changes
thanks @jeanniefinks for these fixes.  The changes to the `help=` strings should also be included in the help text at the top of the file since the help text is generated from these `help=` strings

2021-04-27 22:29 UTC, jeanniefinks reviewed
Made updates; think I got them all.

2021-04-28 15:08 UTC, NMsasa approved these changes

2021-04-29 19:51 UTC, bfineran approved these changes

2021-04-29 19:55 UTC, merged