Updating deepsparse vni check to use hasattr
neuralmagic/sparseml pull request #210
Opened 2021-05-01 20:01 UTC by kevinaer

Catches edge case where if vni is not installed, error is thrown instead of warning

2021-05-02 02:43 UTC, bfineran requested changes
the error here may actually be that the field we're looking for should be `vnni` instead of `vni`.

https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/cpu.py#L51

if this is the case we'd also have to fix this line in the deepsparse framework info: https://github.com/neuralmagic/sparseml/blob/main/src/sparseml/deepsparse/framework/info.py#L119

2021-05-02 14:00 UTC, kevinaer commented
Great catch Ben, completely missed the spelling issue as well!

2021-05-03 02:29 UTC, bfineran approved these changes

2021-05-03 14:50 UTC, markurtz approved these changes

2021-05-03 14:51 UTC, merged