[OneShot] Update unit tests
neuralmagic/sparseml pull request #2231
Opened 2024-04-08 19:16 UTC by dsikka

2024-04-09 18:11 UTC, Satrat approved these changes
Looks great, I'm liking the new unittest layout, it does make things a lot clearer

2024-04-15 07:27 UTC, dbogunowicz commented
@dsikka I see general refactoring here, moving to unittests from pytest, and using the `requires_torch` util. Is there additional RelEng-related context involved as well? Can we talk about this during our 1v1 today?

2024-04-15 07:27 UTC, dbogunowicz approved these changes

2024-04-15 15:06 UTC, bfineran approved these changes

2024-04-16 14:54 UTC, Satrat requested changes
Should've caught this on the first review, but there are requires_torch in places that it shouldnt be needed. Otherwise this looks good to me!

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/modifiers/logarithmic_equalization/test_base.py
> +@requires_torch
Lol I realize this one is my fault but none of the base tests should require torch

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/modifiers/pruning/sparsegpt/test_base.py
> +@requires_torch
Same here, anything under tests/sparseml/modifiers shouldn't need torch, torch is needed by tests/sparseml/pytorch/modifiers

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/modifiers/pruning/wanda/test_base.py
> +@requires_torch
and here

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/modifiers/quantization/test_base.py
> +@requires_torch
and here

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/modifiers/smoothquant/test_base.py
> +@requires_torch
and here

2024-04-16 14:54 UTC, Satrat commented on tests/sparseml/pytorch/modifiers/logarithmic_equalization/test_pytorch.py
> +@requires_torch
and here

2024-04-16 15:07 UTC, Satrat submitted a review, later dismissed

2024-04-16 15:44 UTC, bfineran submitted a review, later dismissed

2024-04-26 16:05 UTC, Satrat approved these changes

2024-04-26 17:02 UTC, dsikka commented on .github/workflows/test-check.yaml
> +        run: pip3 install .[dev,torchvision,onnxruntime] safetensors>=0.4.1
it's already in transformers. We dont need the other dependencies (at least no until my next PR)

2024-04-26 18:07 UTC, bfineran approved these changes

2024-04-26 20:36 UTC, merged