add cli and oneshot pathway smoke tests
neuralmagic/sparseml pull request #2235
Opened 2024-04-09 20:25 UTC by dsikka

2024-04-10 13:29 UTC, Satrat requested changes
LGTM, just a few small change requests on which args to use

2024-04-10 13:45 UTC, dsikka commented on tests/sparseml/pytorch/oneshot/test_cli.py
> +            "10",
Is it toggled between True and False? Or do we always just False?

2024-04-10 14:15 UTC, Satrat commented on tests/sparseml/pytorch/oneshot/test_cli.py
> +            "10",
Should always be False for oneshot, it won't break if its true but will skew the results a bit

2024-04-10 15:22 UTC, Satrat commented on tests/sparseml/pytorch/oneshot/test_inputs.py
> +# TODO: update once this lands: https://github.com/neuralmagic/sparseml/pull/2202
This just landed, lets use the example from that PR in this test

2024-04-15 15:03 UTC, bfineran submitted a review, later dismissed

2024-04-16 18:13 UTC, bfineran submitted a review, later dismissed

2024-04-24 18:17 UTC, Satrat submitted a review, later dismissed

2024-04-26 21:01 UTC, bfineran approved these changes

2024-04-26 21:09 UTC, Satrat approved these changes

2024-04-27 01:27 UTC, merged