non-parameterized torch QAT MatMul Module
neuralmagic/sparseml pull request #283
Opened 2021-06-11 20:48 UTC by bfineran

to help in efforts of quantizing more parts of transformer graphs. This module is to be used in place of `torch.matmul` and will export to ONNX (before quantization conversion) as follows:
<img width="329" alt="Screen Shot 2021-06-11 at 4 47 08 PM" src="https://user-images.githubusercontent.com/11316925/121746989-b1374900-cad4-11eb-98f5-83a88c1f5ad1.png">

This graph will be able to be converted to a single `QLinearMatMul` op with additional post processing to be added in a future PR.

2021-07-01 19:49 UTC, natuan approved these changes, later dismissed

2021-07-02 18:57 UTC, markurtz commented
Talked with @bfineran and @natuan on this, I'm concerned about two points on this direction:
- requiring sparseml for the model definition now which we've been avoiding as much as possible previously
- a design pattern that is more flexible for the future of including more functional operators for quantization

2021-07-16 16:07 UTC, markurtz requested changes
As discussed for next release (0.7) we'll go through and implement a more generic version

2021-08-04 18:37 UTC, bfineran commented
closing in favor of #353

2021-08-04 18:37 UTC, closed without merging