One shot MFAC pruning support
neuralmagic/sparseml pull request #305
Opened 2021-06-23 21:49 UTC by bfineran

One shot pruning support for WoodFisher / MFAC. This requires extra support because the method needs a certain number of gradient samples to prune with.  Support is added by offering `dataloader` and `loss_fn` kwargs that will be used to obtain the required samples.

Testing with dummy data/loss function passes through the MFAC pipeline:
Recipe contains - 
```yaml
  - !MFACGlobalPruningModifier
    params: "__ALL_PRUNABLE__"
    init_sparsity: 0.0
    final_sparsity: *target_sparsity
    start_epoch: *pruning_start_epoch
    end_epoch: *pruning_end_epoch
    update_frequency: *pruning_update_frequency
    mask_type: *pruning_mask_type
```

Sample code - 
```python
from sparseml.pytorch.optim import ScheduledModifierManager
import torch
from torchvision.models import resnet50

RECIPE_PATH = ""

r = resnet50(False)
manager = ScheduledModifierManager.from_yaml(RECIPE_PATH)

dataloader = (torch.randn(10,3,224,224) for _ in range(200))
loss_fn = lambda x: torch.mean(x)

manager.apply(r, dataloader=dataloader, loss_fn=loss_fn)
```

2021-07-16 21:09 UTC, markurtz requested changes

2021-07-16 21:09 UTC, markurtz commented on src/sparseml/pytorch/utils/mfac_helpers.py
> +    @staticmethod
static method won't allow the implementer to override -- should probably change out for class or instance if we expect there's any chance they'll need to access state

2021-07-16 21:09 UTC, markurtz commented on src/sparseml/pytorch/utils/mfac_helpers.py
> +        if isinstance(data, Tensor):
would it make sense to use the tensors_module_forward function here ideally making it more robust and generic?

2021-07-16 21:09 UTC, markurtz commented on src/sparseml/pytorch/utils/mfac_helpers.py
> +        self._loss_fn = loss_fn
NIT: check if loss_fn is callable and dataloader is iterable

2021-08-25 21:58 UTC, markurtz approved these changes
LGTM

2021-08-25 22:13 UTC, rahul-tuli approved these changes
LGTM!
![](https://media1.giphy.com/media/E1Kd3pQwrsMtQbNkt0/giphy.gif)

2021-08-25 22:15 UTC, merged