[WIP] Onnx benchmark
neuralmagic/sparseml pull request #354
Opened 2021-08-04 20:08 UTC by kevinaer

Changes:
- Added `check_onnxruntime_gpu_install` and `require_onnxruntime_gpu` annotation
- Added ORT Benchmark runners for CPU, CUDA, and generic ORT with user provided execution provider
- Updated DeepSparseModelRunner to take in all inputs that `compile_model` takes in
- Added `create_benchmark_runner` and `run_benchmark` to call into from `sparseml.benchmark` command

TODO:
- Tests

2021-08-11 21:32 UTC, markurtz requested changes

2021-08-11 21:32 UTC, markurtz commented on setup.py
> +    "pytest-mock>=3.6.1",
🥑

2021-08-11 21:32 UTC, markurtz commented on src/sparseml/onnx/base.py
> +    "onnxruntime_gpu_installed",
I'm not sold on the additional checks for a specific provider type. ORT has a lot of providers that we may want to support in the future, can we make something more generic here for checking for a given provider or list of providers?

2021-08-11 21:32 UTC, markurtz commented on src/sparseml/onnx/benchmark/info.py
> +class ORTCudaBenchmarkRunner(ORTBenchmarkRunner):
I'm worried about this scaling as well across all of the different providers we may want to support in the future for ORT. Is there anyway to make this more generic and set a provider or list of providers arg and then run checks based on that?

2021-08-26 13:48 UTC, markurtz submitted a review, later dismissed
LGTM, left a small comment

2021-08-27 15:49 UTC, markurtz approved these changes

2021-09-07 14:13 UTC, bfineran approved these changes

2021-09-07 14:51 UTC, merged