QAT and quant postprocessing for torch.nn.Embedding
neuralmagic/sparseml pull request #374
Opened 2021-09-03 17:50 UTC by bfineran

Embedding layers are a large storage requirement for transformer models. This PR introduces a pathway to quantize embedding values. By default this behavior will be enabled by the `QuantizationModifier`

## Python Example
```python
>>> import torch
>>> from sparseml.pytorch.optim import QuantizationModifier
>>> module = torch.nn.Embedding(100, 100)
>>> QuantizationModifier().apply(module)
>>> module
Embedding(
  100, 100
  (activation_post_process): FakeQuantize(
    fake_quant_enabled=tensor([1], dtype=torch.uint8), observer_enabled=tensor([1], dtype=torch.uint8),            quant_min=0, quant_max=255, dtype=torch.quint8, qscheme=torch.per_tensor_affine, ch_axis=-1,         scale=tensor([1.]), zero_point=tensor([0])
    (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
  )
  (weight_fake_quant): FakeQuantize(
    fake_quant_enabled=tensor([1], dtype=torch.uint8), observer_enabled=tensor([1], dtype=torch.uint8),            quant_min=-128, quant_max=127, dtype=torch.qint8, qscheme=torch.per_tensor_affine, ch_axis=-1,         scale=tensor([1.]), zero_point=tensor([0])
    (activation_post_process): MovingAverageMinMaxObserver(min_val=inf, max_val=-inf)
  )
)
```

## FP32 ONNX Graph
<img width="717" alt="Screen Shot 2021-09-03 at 1 48 09 PM" src="https://user-images.githubusercontent.com/11316925/132046895-5ccc8b4f-76e2-4f4a-83e1-dece39f95c40.png">

## QAT ONNX Graph
<img width="264" alt="Screen Shot 2021-09-03 at 1 48 16 PM" src="https://user-images.githubusercontent.com/11316925/132046910-1ae0a4ab-c48c-4aef-acfc-c18c1849ee30.png">

## Quant ONNX Graph
<img width="691" alt="Screen Shot 2021-09-03 at 1 48 31 PM" src="https://user-images.githubusercontent.com/11316925/132046939-7f83d750-a9ba-431c-b5c4-abde6f6a7922.png">

2021-09-06 16:54 UTC, markurtz requested changes
Overall looks good, a few small comments

2021-09-06 16:54 UTC, markurtz commented on src/sparseml/pytorch/optim/modifier_quantization.py
> +        using sparseml.pytorch.utils.quantization.prepare_embeddings_qat to fake
doc strings need to be indented for proper parsing

2021-09-06 16:54 UTC, markurtz commented on src/sparseml/pytorch/optim/modifier_quantization.py
> +        using sparseml.pytorch.utils.quantization.prepare_embeddings_qat to fake
doc strings need to be indented for proper parsing

2021-09-06 16:54 UTC, markurtz commented on src/sparseml/pytorch/optim/modifier_quantization.py
> +        quantize embedding weights. Default is True
Let's add a note in here that it won't do anything for models that don't contain embeddings since our default is True

2021-09-07 14:30 UTC, markurtz approved these changes

2021-09-08 14:38 UTC, mgoin approved these changes

2021-09-08 14:40 UTC, rahul-tuli approved these changes
![](https://media4.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-medium.gif)

2021-09-08 15:45 UTC, merged