Revised distillation modifier
neuralmagic/sparseml pull request #398
Opened 2021-10-04 03:42 UTC by natuan

I made the following changes to the distillation modifier:
- Removed the use of forward hook to capture the latest inputs/outputs because it ignores the kwargs dict passed in to model forward (which is the type of model inputs, e.g. in QA model)
- Removed the computation of teacher outputs inside the modifier's loss_update. Passing in the entire inputs dict into the teacher forward causes cross entropy loss to be calculated, which we don't need; it also creates an issue downstream from autograd when doing loss.backward.

2021-10-06 14:06 UTC, markurtz requested changes
@natuan our goal is to remove as much complexity for the user with modifiers as possible. This implementation is adding more complexity back to the user, specifically needing to manage the complete lifecycle of the teacher model themselves now. Additionally, the old code, as set up, would work for other pipelines and reduce simplicity for users.

2021-10-06 14:06 UTC, markurtz commented on src/sparseml/pytorch/optim/modifier_distillation.py
> +        if student_outputs is None or teacher_outputs is None:
We shouldn't silently ignore here, if the user passed in something wrong it's impossible to tell that it isn't working correctly

2021-10-07 12:25 UTC, markurtz approved these changes

2021-10-07 12:47 UTC, bfineran approved these changes
LGTM

2021-10-07 13:38 UTC, merged