ONNX export API and script for transformers
neuralmagic/sparseml pull request #497
Opened 2022-01-06 22:17 UTC by bfineran

accessible via `sparseml.transformers.export_onnx --task <TASK> --model_path <MODEL_PATH>`

loads the model, recipe, config, and tokenizer from model directory. creates a fake batch of size 1 from tokenizer that is passed directly to the model for export

2022-01-06 22:49 UTC, rahul-tuli requested changes

2022-01-06 22:49 UTC, rahul-tuli commented on src/sparseml/transformers/utils/export.py
> +    parser = argparse.ArgumentParser(
Add doctstring or make function private `_parse_args`

2022-01-06 22:49 UTC, rahul-tuli commented on src/sparseml/transformers/utils/export.py
> +def parse_args() -> argparse.ArgumentParser:
nit: return type is `argparse.Namespace`

2022-01-06 22:49 UTC, rahul-tuli commented on src/sparseml/transformers/utils/export.py
> +        help="task to create the model for. i.e. mlm, qa, glue, ner",
nit: Use title case for first word, `Task`. Or make every help string start with lowercase

2022-01-06 22:49 UTC, rahul-tuli commented on src/sparseml/transformers/utils/export.py
> +            "optional finetuning task for text classification and token "
nit: Capitalize `O`

2022-01-06 22:49 UTC, rahul-tuli commented on src/sparseml/transformers/utils/export.py
> +            "name for exported ONNX file in the model directory. "
nit: Capitalize `N`

2022-01-07 03:35 UTC, rahul-tuli submitted a review, later dismissed
<img src="https://media0.giphy.com/media/26gsobowozGM9umBi/giphy.gif"/>

2022-01-12 14:09 UTC, markurtz approved these changes

2022-01-12 22:11 UTC, rahul-tuli approved these changes

2022-01-12 22:46 UTC, markurtz approved these changes

2022-01-12 22:56 UTC, merged