ViT Integration
neuralmagic/sparseml pull request #500
Opened 2022-01-11 19:11 UTC by KSGulin

- Add: setup_integration.sh
- Update: Readme.md
- Remove: train.py

2022-01-11 19:36 UTC, rahul-tuli requested changes

2022-01-11 19:36 UTC, rahul-tuli commented on integrations/rwightman-timm/README.md
> +[`train.py` script](https://github.com/neuralmagic/yolact/blob/master/train.py).
```suggestion
[`train.py` script](https://github.com/neuralmagic/pytorch-image-models/blob/master/train.py).
```

2022-01-11 19:36 UTC, rahul-tuli commented on integrations/rwightman-timm/README.md
> +Popular recipes used with this argument are found in the [`recipes` folder](./recipes).
No recipes folder in the repo yet

2022-01-11 19:36 UTC, rahul-tuli commented on integrations/rwightman-timm/README.md
> +| tutorials            | Tutorial walkthroughs for how to sparsify ViT models using recipes (WIP).                                                   |          |
making a note here, as a reminder to push out the recipes and tutorial

2022-01-11 19:36 UTC, rahul-tuli commented on integrations/rwightman-timm/README.md
> +After sparsifying a model, the `export.py` script can be run to convert the model into an [ONNX](https://onnx.ai/) deployment format.
Add a link to `export.py`

2022-01-11 19:43 UTC, rahul-tuli commented
Looks good to me overall, minor nits; I didn't take a super close looks at the training and export commands though

2022-01-12 22:29 UTC, markurtz commented on integrations/rwightman-timm/README.md
> +Using a local recipe and checkpoint, a pruning a model can be done by running the following command from within the root of this integration's folder
```suggestion
Using a local recipe and checkpoint, pruning a model can be done by running the following command from within the root of this integration's folder
```

2022-01-12 22:32 UTC, markurtz requested changes

2022-01-12 22:32 UTC, markurtz commented on integrations/rwightman-timm/setup_integration.sh
> +cd pytorch-image-models
@KSGulin we should add a release branch on the timm repo and change to that branch here so we can guarantee ongoing changes and improvements won't affect the latest stable release

2022-01-12 22:34 UTC, rahul-tuli approved these changes, later dismissed

2022-01-12 22:34 UTC, rahul-tuli commented on integrations/rwightman-timm/README.md
> +The `setup_integration.sh` file will clone the pytorch-image-models repository with the SparseML integration as a subfolder.
nit: link the repo
```suggestion
The `setup_integration.sh` file will clone the [pytorch-image-models](https://github.com/neuralmagic/pytorch-image-models.git) repository with the SparseML integration as a subfolder.
```

Can also put an anchor at the end of the file ass follows:
```
[pytorch-image-models]: https://github.com/neuralmagic/pytorch-image-models.git
```
and then use `[pytorch-image-models]` everywhere

2022-01-12 22:34 UTC, rahul-tuli commented on integrations/rwightman-timm/setup_integration.sh
> +pip install -r requirements.txt
nit: newline

2022-01-12 22:43 UTC, bfineran approved these changes

2022-01-12 22:47 UTC, markurtz approved these changes

2022-01-12 22:47 UTC, rahul-tuli approved these changes

2022-01-12 22:48 UTC, merged