Enforce order on input keys to export
neuralmagic/sparseml pull request #545
Opened 2022-02-07 19:16 UTC by natuan

Putting back the order of input's keys passing into the pytorch onnx export

2022-02-07 19:20 UTC, bfineran submitted a review, later dismissed

2022-02-07 19:21 UTC, markurtz requested changes
@natuan need to regenerate the input_shapes arg based on the new inputs that will be passed through so we log properly. Additionally, can we add a warning in the event that the keys in the inputs do not match the keys for the forwards.

2022-02-07 19:34 UTC, natuan commented
> @natuan need to regenerate the input_shapes arg based on the new inputs that will be passed through so we log properly. Additionally, can we add a warning in the event that the keys in the inputs do not match the keys for the forwards.

I fixed the first one you mentioned. For the warning, the input output by the tokenizer is a Dict so by issuing that warning we imply an ordering over it right? (which is what this fix is) In the pytorch/utils/exporter we did have this type of warning if the input batch is a Dict but not an OrderedDict

2022-02-07 20:59 UTC, markurtz commented
> > @natuan need to regenerate the input_shapes arg based on the new inputs that will be passed through so we log properly. Additionally, can we add a warning in the event that the keys in the inputs do not match the keys for the forwards.
> 
> I fixed the first one you mentioned. For the warning, the input output by the tokenizer is a Dict so by issuing that warning we imply an ordering over it right? (which is what this fix is) In the pytorch/utils/exporter we did have this type of warning if the input batch is a Dict but not an OrderedDict

I was mainly concerned that we are now technically filtering out inputs based on whether or not they are defined in the forward function. This is something that might be a good thing to do, but we should have a warning in place to say that the inputs were filtered and not everything was passed through. On the other side, if not all inputs are found that are defined in the forward, it would be good to have this called out as well in the event that some have defaults and therefore would not fail the forward

2022-02-08 18:51 UTC, markurtz approved these changes

2022-02-08 18:51 UTC, bfineran approved these changes

2022-02-08 18:52 UTC, markurtz approved these changes

2022-02-08 18:52 UTC, merged