stages support for Manager lifecycle
neuralmagic/sparseml pull request #562
Opened 2022-02-18 21:47 UTC by bfineran

this pull request add support for `Manager` to run and save staged recipes in the form of a `Dict[str, List[BaseManager]]`. Marking WIP until further testing is complete

2022-02-19 01:44 UTC, bfineran commented on src/sparseml/optim/manager.py
> +            self._modifiers = dict(
Need to use ordered dict

2022-02-23 12:08 UTC, dbogunowicz requested changes
Looks good to me, after merging those changes into my branch, everything seems to be working as expected. Please take care of the pending failing test  in `tests/sparseml/pytorch/optim/test_modifier.py::test_load_list_fails`

2022-02-24 12:56 UTC, dbogunowicz approved these changes

2022-02-24 16:51 UTC, markurtz approved these changes

2022-02-24 17:04 UTC, merged