Update SparseML to support Pytorch 1.10.0
neuralmagic/sparseml pull request #569
Opened 2022-02-24 12:38 UTC by dbogunowicz

2022-02-24 16:31 UTC, bfineran requested changes
torch 1.10.2 is out and stable, any reason this isn't included in the range?

2022-03-04 21:20 UTC, bfineran approved these changes, later dismissed

2022-03-07 09:30 UTC, rahul-tuli submitted a review, later dismissed
The PR is approved barring one small outdated comment, real nice work with the tests. Good work!

2022-03-07 09:30 UTC, rahul-tuli commented on src/sparseml/pytorch/base.py
> +_TORCH_MAX_VERSION = "1.10.100"  # set bug to 100 to support all future 1.9.X  versions
update comment
```suggestion
_TORCH_MAX_VERSION = "1.10.100"  # set bug to 100 to support all future 1.10.X  versions
```

2022-03-07 09:30 UTC, rahul-tuli commented on tests/sparseml/onnx/optim/test_analyzer_model.py
> +    assert any(result)
nice

2022-03-07 09:36 UTC, dbogunowicz commented on src/sparseml/pytorch/base.py
> +_TORCH_MAX_VERSION = "1.10.100"  # set bug to 100 to support all future 1.9.X  versions
Nice catch! Thank you!

2022-03-07 09:46 UTC, rahul-tuli approved these changes

2022-03-07 11:40 UTC, KSGulin approved these changes
Nice! LGTM

2022-03-07 11:57 UTC, merged