make build argument for nightly builds
neuralmagic/sparseml pull request #63
Opened 2021-02-04 21:50 UTC by bfineran

this PR introduces a Makefile argument and modifies `setup.py` so nightly packages can be built with
```
make build BUILD_ARGS=nightly
```

`dist` directory contents after building:
```
sparseml_nightly-0.1.0-py3-none-any.whl  sparseml-nightly-0.1.0.tar.gz
```

2021-02-04 21:56 UTC, dhuangnm requested changes
Hi Ben,

For nightly build, the version also needs to have a fourth part which is the build date in the format of "yyyymmdd", e.g.:

sparseml_nightly-0.1.0.20210204-py3-none-any.whl

Thanks,
Dan

2021-02-04 22:17 UTC, bfineran commented
Thanks Dan, I updated `setup.py` to use this nightly versioning format.

2021-02-04 22:37 UTC, mgoin approved these changes

2021-02-05 19:59 UTC, markurtz approved these changes

2021-02-08 02:58 UTC, dhuangnm approved these changes
Looks good, thanks Ben!

2021-02-08 03:24 UTC, merged