[MFAC] cache previous GPUtil return
neuralmagic/sparseml pull request #650
Opened 2022-03-28 16:06 UTC by KSGulin

2022-03-28 16:33 UTC, rahul-tuli requested changes
Lgtm once the wrapper is wrapped in `functools.wraps`

2022-03-28 16:33 UTC, rahul-tuli commented on src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
> +    def wrapper(*args):
can we change the name to something more intuitive rather than just `wrapper`?

2022-03-28 16:33 UTC, rahul-tuli commented on src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
> +
Can we wrap inside a `@functools.wraps` to preserve info about the decorated function?

2022-03-28 17:02 UTC, bfineran requested changes
shouldn't we account for the device idx in the cache?

2022-03-28 17:02 UTC, bfineran commented on src/sparseml/pytorch/sparsification/pruning/modifier_pruning_mfac.py
> +def cache_return(func):
nit: rename since specific to gpu mem func

2022-03-28 17:08 UTC, rahul-tuli approved these changes, later dismissed

2022-03-28 17:21 UTC, KSGulin commented
> shouldn't we account for the device idx in the cache?

@bfineran `_get_free_gpu_memory` returns available memory in same order that PyTorch sees the devices in, so there is no need to track device idx

2022-03-28 18:16 UTC, KSGulin commented
@bfineran @rahul-tuli Updated to track device idx after all. In case the function is re-purposed for different flows

2022-03-28 22:16 UTC, bfineran requested changes
one more requested change - if for some reason there's a failure and the cache is empty, we will get a `KeyError`, we should definitely raise a `RuntimeException` or something similar if they key is not found in cache

2022-03-28 22:16 UTC, bfineran commented
also looks like quality is red @KSGulin

2022-03-28 22:20 UTC, KSGulin commented
@bfineran if cache is empty it returns an empty list, which the rest of the MFAC modifier takes as a signal to use CPU. The quality error is not replicated locally. Will investigate further

2022-03-28 23:23 UTC, bfineran commented
@KSGulin ah yup, if a user specifies that GPU should be used though, we should at least warn if falling back to CPU

2022-03-29 12:05 UTC, KSGulin commented
@bfineran good point, warning added.

2022-03-29 15:17 UTC, bfineran approved these changes

2022-03-29 21:14 UTC, markurtz approved these changes

2022-03-29 21:45 UTC, merged