[Composed Recipes] IC integration
neuralmagic/sparseml pull request #705
Opened 2022-04-14 12:56 UTC by dbogunowicz

2022-04-15 13:56 UTC, dbogunowicz commented on src/sparseml/pytorch/image_classification/utils/trainer.py
> +        checkpoint_manager.apply(self.model)
@rahul-tuli how is it different from apply structure.

2022-04-15 13:56 UTC, dbogunowicz commented on src/sparseml/pytorch/image_classification/utils/trainer.py
> +        checkpoint_manager.apply(self.model)
@rahul-tuli how is it different from apply structure.

2022-04-25 23:16 UTC, KSGulin submitted a review, later dismissed
Great stuff!

2022-04-26 23:26 UTC, bfineran requested changes
@dbogunowicz LGTM, looks like we may be missing one more piece - need to call `apply_structure` on the checkpoint recipe before loading weights
(see #481 for an early hack of this).

The affected function is `load_model` in `pytorch/utils/model.py`. Can close #481 once that functionality is added here

2022-04-27 13:36 UTC, dbogunowicz commented
> @dbogunowicz LGTM, looks like we may be missing one more piece - need to call `apply_structure` on the checkpoint recipe before loading weights (see #481 for an early hack of this).
> 
> The affected function is `load_model` in `pytorch/utils/model.py`. Can close #481 once that functionality is added here

Thank you for reminding me. This was buried in my git stash and committed...
While at it, I spent some time resolving merge conflicts and integrating with click. The current version is manually tested and ready for next round of reviews.

2022-05-03 15:50 UTC, bfineran reviewed
lgtm pending suggestion

2022-05-03 15:50 UTC, bfineran commented on src/sparseml/pytorch/utils/model.py
> +        epoch = model_dict.get("epoch", 0.0)
```suggestion
        epoch = model_dict.get("epoch", float("inf"))
```

2022-05-05 22:23 UTC, bfineran approved these changes

2022-05-09 11:07 UTC, KSGulin approved these changes

2022-05-09 14:11 UTC, merged