ultralytics/yolov5 integration
neuralmagic/sparseml pull request #73
Opened 2021-02-14 00:09 UTC by bfineran

2021-02-14 00:11 UTC, bfineran commented
this first commit includes requirements for running recipes within the yolov5 training script as well as a SparseZoo integration for recipes and checkpoint files.  testing is WIP and is blocked by other resource priorities

2021-02-14 17:13 UTC, mgoin approved these changes, later dismissed
cool, docs and integration looks really clean to me. accepting now assuming that we'll have testing added in later work

2021-02-14 17:13 UTC, mgoin commented on examples/ultralytics-sparseml/README.md
> +`examples/timm-sparseml/main.py` modifies
should this be `examples/ultralytics-sparseml/main.py`?

2021-02-14 17:13 UTC, mgoin commented on examples/ultralytics-sparseml/README.md
> +`zoo:cv/detection/yolo_v3-spp/pytorch/ultralytics/coco/pruned-aggressive`.
i didn't know you could use the model stub as recipe path, that's really nice

2021-02-17 20:52 UTC, markurtz requested changes
Same overall comments as the rwightman integration:
- migrate it over to your suggestion of having a folder for integrations
- name the root just ultralytics since we're already in the sparseml repo
- remove path from the arg since this supports both paths and stubs for sparseml-recipe-path
- change out functionality for sparse-transfer-learn to be more generic for sparsezoo-recipe-type
- issues with using min_epoch from manager
- logging for when we're overriding something such as with the number of epochs

2021-02-17 20:52 UTC, markurtz commented on examples/ultralytics-sparseml/README.md
> +repository also known as [timm](https://pypi.org/project/timm/).
left over timm reference

2021-02-17 20:52 UTC, markurtz commented on examples/ultralytics-sparseml/main.py
> +    scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)
If the recipe is overriding the LR, we should likely kill the scheduler here

2021-02-17 20:54 UTC, markurtz commented
Oh also, can we get the exact checkpoint of the integrated repo this was tested with in the even people have issues with newer versions?

2021-02-23 03:43 UTC, bfineran commented
Thanks for review @markurtz @mgoin should be up to date with reviews now

2021-02-23 05:14 UTC, mgoin submitted a review, later dismissed
LGTM

2021-02-23 11:37 UTC, markurtz requested changes

2021-02-23 11:37 UTC, markurtz commented on integrations/ultralytics/README.md
> +`integrations/ultralytics/main.py` modifies
One more small change that I missed, can we rename this file to train.py? This way there is a one to one mapping without a lookup of names for the file(s) in the integration repo to the files stored in sparseml

2021-02-23 15:22 UTC, markurtz approved these changes, later dismissed

2021-02-23 15:24 UTC, mgoin submitted a review, later dismissed

2021-02-23 19:58 UTC, bfineran commented on integrations/ultralytics/train.py
> +    parser.add_argument('--weights', type=str, default='yolov5s.pt', help='initial weights path')
```suggestion
```

2021-02-23 20:55 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +* quantization-aware-training
```suggestion
* quantization-aware training
```

2021-02-23 20:55 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +* sparse quantization-aware-training
```suggestion
* sparse quantization-aware training
```

2021-02-23 21:13 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +To use both the script, clone both repositories, install their dependencies,
```suggestion
To use the scripts, clone both repositories, install their dependencies,
```

2021-02-23 21:14 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +* Modifiers will log their outputs to the console as well as to the tensorboard file
```suggestion
* Modifiers will log their outputs to the console as well as to the TensorBoard file
```

2021-02-23 21:17 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +may conflict with each other causing unintended side effects, choose
```suggestion
may conflict with each other causing unintended side effects, so choose
```

2021-02-23 21:17 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +hyperparameters accordingly.
```suggestion
hyperparameters accordingly
```

2021-02-23 22:58 UTC, markurtz approved these changes, later dismissed

2021-02-23 23:02 UTC, jeanniefinks commented on integrations/ultralytics/README.md
> +  <regular yolov5/train.py paramters>
```suggestion
  <regular yolov5/train.py parameters>
```

2021-02-23 23:04 UTC, jeanniefinks approved these changes, later dismissed
minor typo fix from me per last comment and you are gtg from me.

2021-02-23 23:09 UTC, mgoin approved these changes, later dismissed

2021-02-24 02:44 UTC, jeanniefinks commented on integrations/ultralytics/train.py
> +            logger.info(f'Start Tensorboard with "tensorboard --logdir {opt.project}", view at http://localhost:6006/')
```suggestion
            logger.info(f'Start TensorBoard with "tensorboard --logdir {opt.project}", view at http://localhost:6006/')
```

2021-02-24 17:39 UTC, markurtz approved these changes

2021-02-24 18:02 UTC, mgoin approved these changes

2021-02-24 18:11 UTC, merged