[Documentation] [General Template] Transformers QnA
neuralmagic/sparseml pull request #736
Opened 2022-04-28 11:30 UTC by dbogunowicz

2022-05-03 11:04 UTC, markurtz commented
@dbogunowicz this looks very good, great job on this! Overall I like the layout and the template. We'll need to update wording a bit so added @jeanniefinks on for that to ensure we have a consistent external voice for users

2022-05-03 13:03 UTC, dtransposed commented
> @dbogunowicz this looks very good, great job on this! Overall I like the layout and the template. We'll need to update wording a bit so added @jeanniefinks on for that to ensure we have a consistent external voice for users

I am thinking whether we can maybe divide this task into two items:
- agreeing on a common convention across templates (so we can kick off with writing docs for other pipelines asap).
- polishing up the single doc.

2022-05-03 13:06 UTC, dbogunowicz commented
> @dbogunowicz this looks very good, great job on this! Overall I like the layout and the template. We'll need to update wording a bit so added @jeanniefinks on for that to ensure we have a consistent external voice for users

I am thinking whether we can maybe divide this task into two items:
- agreeing on a common convention across templates (so we can kick off with writing docs for other pipelines asap).
- polishing up the single doc.

2022-05-03 17:05 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +## Getting started
```suggestion
## Getting Started
```

2022-05-03 17:08 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +To learn more, please refer to the [appropriate documentation in the DeepSparse repository](https://github.com/neuralmagic/deepsparse/tree/main/examples/huggingface-transformers)
```suggestion
To learn more, refer to the [appropriate documentation in the DeepSparse repository](https://github.com/neuralmagic/deepsparse/tree/main/examples/huggingface-transformers)
```

2022-05-03 18:24 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +In the example below, we fetch a pruned, quantized BERT model, pre-trained on Wikipedia and Bookcorpus datasets. We then fine tune the model to the SQuAD dataset.
```suggestion
In the example below, we fetch a pruned, quantized BERT model, pre-trained on Wikipedia and Bookcorpus datasets. We then fine-tune the model to the SQuAD dataset. 
```

2022-05-03 18:27 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +Alternatively, the user may decide to train their own dense teacher model. The following command will use the dense BERT base model from the SparseZoo and fine-tune it on the SQuAD dataset.
```suggestion
Alternatively, the user may decide to train their own dense teacher model. The following command uses the dense BERT base model from the SparseZoo and fine-tunes it on the SQuAD dataset.
```

2022-05-03 18:28 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +The SparseML installation provides a CLI for sparsifying your models for a specific task; appending the `--help` argument will provide a full list of options for training in SparseML:
```suggestion
The SparseML installation provides a CLI for sparsifying your models for a specific task; appending the `--help` argument displays a full list of options for training in SparseML:
```

2022-05-03 18:33 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answer.md
> +The deployment is intuitive and simple thanks to DeepSparse Python API.
```suggestion
The deployment is intuitive due to the DeepSparse Python API.
```

2022-05-03 18:46 UTC, jeanniefinks requested changes
For technical writing style, please 

- do not use "please" or "thanks/thank you."
- use present simple tense in most cases

Include how users get help; add as a new paragraph to bottom:

For Neural Magic Support, sign up or log in to our **[Deep Sparse Community Slack](https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ).** Bugs, feature requests, or additional questions can also be posted to our [GitHub Issue Queue.](https://github.com/neuralmagic/sparseml/issues)

2022-05-05 08:11 UTC, dbogunowicz commented
Just a reminder, that we should probably remove my general "template" comments before this lands as a doc for the users.

2022-05-05 12:30 UTC, bfineran approved these changes

2022-05-06 07:33 UTC, dbogunowicz commented
@mgoin not really sure who would be a good person to ask, but I guess that's you:
do you have any thoughts on sprinkling some consistent "beautifications" on the docs? I am talking specifically about e.g. adding emoticons to the section headers.

2022-05-06 13:47 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +  --cache_dir cache \                               # local directory to store the downloaded hugging face model."
```suggestion
  --cache_dir cache \                               # local directory to store the downloaded hugging face model.  
```

2022-05-06 13:56 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +    --task 'question-answering' \
```suggestion
    --task 'question-answering' 
```

2022-05-27 14:36 UTC, rahul-tuli submitted a review, later dismissed

2022-05-27 17:10 UTC, KSGulin reviewed
Thanks for putting together this template @dbogunowicz. It was really helpful in writing the rest of the docs. I left some comments and suggestions.

2022-05-31 09:13 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +SparseML Question Answer pipeline integrates with Hugging Face’s Transformers library to enable the sparsification of any transformer model.
Right.

2022-05-31 09:15 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +SparseML Question Answer pipeline integrates with Hugging Face’s Transformers library to enable the sparsification of any transformer model.
```suggestion
SparseML Question Answer pipeline integrates with Hugging Face’s Transformers library to enable the sparsification of a large set of transformers models.
```

2022-05-31 09:16 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +Sparse ML Hugging Face Question Answer integration allows sparsifying any dense transformer.
Good point.

2022-05-31 09:16 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +Sparse ML Hugging Face Question Answer integration allows sparsifying any dense transformer.
```suggestion
```

2022-06-01 15:08 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answering.md
> +- **Sparse Transfer Learning** - fine-tune a sparse backbone model (or use one of our [sparse pre-trained models](https://sparsezoo.neuralmagic.com/?page=1&domain=nlp&sub_domain=question_answering))
```suggestion
- **Sparse Transfer Learning** - fine-tune a sparse backbone model (or use one of our [sparse pre-trained models](https://sparsezoo.neuralmagic.com/?page=1&domain=nlp&sub_domain=question_answering)) on your own private dataset.
```

2022-06-01 15:12 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answering.md
> +# SparseML Transformer Question Answer Integration
should it really be:
SparseML Transformer Question Answering Integration

2022-06-01 15:26 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answering.md
> +SparseML Question Answer pipeline integrates with Hugging Face’s Transformers library to enable the sparsification of a large set of transformers models.
Question Answer = Question Answering (?)

2022-06-01 16:08 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answering.md
> +By modifying the `distill_teacher` argument, you can enable [Knowledge Destillation](https://neptune.ai/blog/knowledge-distillation) (KD) functionality.
```suggestion
By modifying the `distill_teacher` argument, you can enable [Knowledge Distillation](https://neptune.ai/blog/knowledge-distillation) (KD) functionality.
```

2022-06-01 16:35 UTC, jeanniefinks requested changes
Left some easy comments to consider.

2022-06-01 16:45 UTC, dbogunowicz commented on src/sparseml/transformers/README_question_answering.md
> +This includes the recipe (with the full description of the sparsification attributes), checkpoint files (saved in the appropriate framework format), Hugging Face Transformer's specific files (e.g. th
@jeanniefinks Not sure whether I want to remove that information, sitting on the fence here. I do not like this paragraph very much, but I think it delivers an important message. Maybe rewording would be the best way out? Or maybe if a third reviewer also finds this paragraph unnecessary I would be ok with removing it.

2022-06-01 20:36 UTC, bfineran commented on src/sparseml/transformers/README_question_answering.md
> +This includes the recipe (with the full description of the sparsification attributes), checkpoint files (saved in the appropriate framework format), Hugging Face Transformer's specific files (e.g. th
I would prefer to keep this change `Hugging Face Transformer's specific files (e.g. the tokenizer), etc.` to `configuration files for the tokenizer and dataset, etc.`

2022-06-01 20:38 UTC, bfineran commented on src/sparseml/transformers/README_question_answering.md
> +from deepsparse.pipeline import Pipeline
```suggestion
from deepsparse import Pipeline
```

2022-06-01 20:38 UTC, bfineran commented on src/sparseml/transformers/README_question_answering.md
> +- Hugging Face Transformer's specific files (e.g., the tokenizer).
```suggestion
- Additional configuration files (e.g. tokenizer, dataset info)
```

2022-06-01 20:38 UTC, bfineran commented on src/sparseml/transformers/README_question_answering.md
> +This includes the recipe (with the full description of the sparsification attributes), checkpoint files (saved in the appropriate framework format), Hugging Face Transformer's specific files (e.g. th
actually, after reading the context above, we can definitely remove as this repeats

2022-06-01 20:39 UTC, bfineran submitted a review, later dismissed
LGTM

2022-06-01 20:43 UTC, mgoin submitted a review, later dismissed
looks nice!

2022-06-01 22:46 UTC, jeanniefinks commented on src/sparseml/transformers/README_question_answering.md
> +- Additional configuration files (e.g. tokenizer, dataset info)
```suggestion
- Additional configuration files (e.g., tokenizer, dataset info).
```

2022-06-01 22:48 UTC, jeanniefinks approved these changes
@bfineran added the tiny suggested edit. Make it happen and I am pre-approving it now!

2022-06-06 12:26 UTC, mgoin approved these changes
ship it!

2022-06-06 16:21 UTC, mgoin approved these changes

2022-06-06 16:22 UTC, merged