Image classification/one shot
neuralmagic/sparseml pull request #779
Opened 2022-05-10 21:54 UTC by rahul-tuli

The goal of this PR is to allow easy one-shot application of recipes to image-classification models.

To accomplish this we add a `--one-shot` argument to `sparseml.image_classification.train` script

The new functionality was tested locally with the following:

```bash
sparseml.image_classification.train \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --dataset imagenette \
    --dataset-path ./datasets/imagenette \
    --arch-key resnet50 \
    --recipe-path zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/pruned-conservative?recipe_type=original \
    --checkpoint-path zoo \
    --one-shot
```

The Output is as follows:
```bash

2022-05-10 17:38:36 __main__     INFO     running on device cuda
2022-05-10 17:38:36 __main__     INFO     running on device cuda
2022-05-10 17:38:36 __main__     INFO     Starting training from epoch 0
2022-05-10 17:38:36 __main__     INFO     Starting training from epoch 0
2022-05-10 17:38:36 __main__     INFO     completed...
2022-05-10 17:38:36 __main__     INFO     completed...
Saving model for epoch -1 to /XXXXXXX/projects/sparseml/src/sparseml/pytorch/image_classification/pytorch_vision/resnet50_imagenette__02 for model-one-shot
2022-05-10 17:38:37 __main__     INFO     layer sparsities:
2022-05-10 17:38:37 __main__     INFO     layer sparsities:
2022-05-10 17:38:37 __main__     INFO     input.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     input.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.0.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.1.3.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.0.identity.conv.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.1.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.2.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.3.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.4.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv1.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv2.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.2.5.conv3.weight: 0.0000
2022-05-10 17:38:37 __main__     INFO     sections.3.0.conv1.weight: 0.0000
2022-05-10 17:38:37 __main_ [...]

2022-05-10 22:00 UTC, bfineran commented on src/sparseml/pytorch/image_classification/train.py
>      if not eval_mode:
let's change this to `... and not trainer.one_shot` so all the `starting training...` logging doesn't print for one shot. can move the final save step at the end of this block out with another check for `eval_mode`

2022-05-11 16:57 UTC, rahul-tuli commented on src/sparseml/pytorch/image_classification/train.py
> +    model, arch_key, checkpoint_path = helpers.create_model(
It creates the trainer with correct local checkpoint_path, this is included in PR #778 , I'll rebase over that and change, the base branch

2022-05-11 17:25 UTC, bfineran requested changes
good catch, left comment on logic flow

2022-05-11 17:26 UTC, bfineran commented on src/sparseml/pytorch/image_classification/utils/trainer.py
> +                self._one_shot()
one shot must be applied whether or not there is a `train_loader`

2022-05-11 17:39 UTC, bfineran commented on src/sparseml/pytorch/image_classification/train.py
> +        if is_main_process and not one_shot
should still load datasets if one shot and info provided

2022-05-11 17:39 UTC, bfineran commented on src/sparseml/pytorch/image_classification/utils/trainer.py
> +        _LOGGER.info("Applied recipe to manager")
nit: change to `applied {recipe} in one-shot`

2022-05-11 20:01 UTC, bfineran approved these changes
<img src="https://media3.giphy.com/media/Zxensy1LgmIOvSXZry/giphy.gif"/>

2022-05-16 11:49 UTC, dbogunowicz approved these changes

2022-05-16 21:18 UTC, merged