Added flows for generating sparsezoo structure to ModuleExporter
neuralmagic/sparseml pull request #79
Opened 2021-02-19 22:34 UTC by kevinaer

- Added flow for exporting Pytorch Modules to SparseZoo structure.
- Small quality fixes

2021-02-23 11:42 UTC, markurtz requested changes
Synced with Kevin on this to make a few changes:
- make sure PIL dependency isn't going to fail for non CV flows
- look into the ModuleTrainer flows that have logic for extracting features and labels from a generic input and reusing here
- look into requiring a more generic iterable instance for the data and the user can optionally supply an iterable for the originals or a callback to recover the original 
- add in optional export of the entire model in a torch.save fashion rather than just saving the state_dict

2021-02-24 15:53 UTC, bfineran commented on src/sparseml/pytorch/utils/exporter.py
> +        sample_batch: Optional[Any] = None,
nit: can we remove `trace`, and just run a trace if a `sample_batch` is provided?

2021-02-24 18:30 UTC, bfineran approved these changes
LGTM

2021-02-24 18:32 UTC, bfineran requested changes

2021-02-24 18:32 UTC, bfineran commented on src/sparseml/pytorch/utils/exporter.py
> +            if sample_batch is None:
nit: unreachable line

2021-02-24 19:00 UTC, bfineran approved these changes
LGTM

2021-03-09 17:05 UTC, markurtz approved these changes

2021-03-15 13:48 UTC, merged