New qatmatmul export
neuralmagic/sparseml pull request #791
Opened 2022-05-17 16:38 UTC by anmarques

A fix for QATMatMult for DistilBERT models changes the ONNX pattern for context layer matmul followed by attention head output matmul when using quantization. The main challenge is that the quantization parameters for these two matmuls come from the same set of Q/DQ ops. This PR adds support for this pattern by converting both matmuls in a single pass.

2022-05-17 16:56 UTC, mgoin commented on src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
> +        if tranpose_node is None or tranpose_node.op_type != "Transpose":
```suggestion
        transpose_node = graph.get_node_single_child(matmul_node)

        # Make sure the output from matmul node is Transpose
        if transpose_node is None or tranpose_node.op_type != "Transpose":
```

2022-05-17 16:56 UTC, mgoin commented on src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
> +        graph = ONNXGraph(model)
could make this graph outside of the loop and regenerate it at the end of the loop if we did the conversion

2022-05-17 18:22 UTC, mgoin approved these changes
thanks!

2022-05-18 15:35 UTC, natuan requested changes

2022-05-18 15:44 UTC, anmarques commented on src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
> +        if transpose_node is None or transpose_node.op_type != "Transpose":
It not only checks for None, though. It may be not None and still fail the condition if the type is not "Transpose".

2022-05-18 15:59 UTC, natuan commented on src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
> +            current_output = reshape_node
nvm, I think you still need to check those nodes

2022-05-18 15:59 UTC, natuan approved these changes

2022-05-18 21:41 UTC, bfineran submitted a review, later dismissed
LGTM pending 1) validate accuracy of a converted transformers model with this pattern 2) validate accuracy of a converted transformers model *without* this pattern

2022-05-18 21:43 UTC, bfineran commented
Leaving approval up, but looks like there are some quality issues to fix!

2022-05-19 12:02 UTC, anmarques commented on src/sparseml/pytorch/sparsification/quantization/quantize_qat_export.py
> +            second_optional_node = graph.get_node_single_child(matmul_node)
You're right

2022-05-19 18:18 UTC, anmarques commented
Comments about second optional node addressed. Quality fixed. Checked accuracy of converted models with new (distilbert 80% VNNI SQUAD) and old patterns (12 layer bert base 80% VNNI SQUAD).

2022-05-19 18:55 UTC, bfineran approved these changes

2022-05-19 19:21 UTC, merged