Integrations testing for transformers
neuralmagic/sparseml pull request #797
Opened 2022-05-18 14:19 UTC by KSGulin

2022-05-18 21:26 UTC, bfineran reviewed
LGTM so far, even though it's not complete here, `test_transformers` shows the flexibility of the framework given how compact it is.  Starting to notice some code that can be shared across integrations for the test impls.

Assuming we are adding in export before merging?

2022-05-19 21:37 UTC, bfineran reviewed
Let's add a config that tests export. Also worried if the deepsparse random data generator is sufficient given items such as attention mask need a specific format. Might be best to have sample tokenizer input given in the config then use the tokenizer to generate sample data. (Can see how this flow may work in our transformers onnx export script)

2022-05-20 15:00 UTC, dbogunowicz approved these changes
Can we remove my (+ Konstantin's) transformers tests from `tests/sparsezoo/transformers` then? They seem to be redundant now.

2022-05-20 15:14 UTC, bfineran requested changes

2022-05-20 15:14 UTC, bfineran commented on tests/integrations/transformers/test_transformers.py
> +            numpy.float32
inputs to the BERT models are INTs I believe, will this run as expected?

2022-05-20 21:06 UTC, rahul-tuli approved these changes

2022-05-20 21:12 UTC, bfineran approved these changes

2022-05-20 21:12 UTC, merged