[Integrations-Testing] Add abridged mode
neuralmagic/sparseml pull request #810
Opened 2022-05-23 14:30 UTC by KSGulin

Add an abridged mode which automatically shortens the run. The currently shortening logic sets the number of train and eval steps to a default value (10 was chosen arbitrarily), but the logic can be expanded to include abridged deploy runs once implemented. Adding this keyword allows for the maintenance of a standardized short run mode.

2022-05-26 11:30 UTC, dbogunowicz commented
What's the point of the abridged mode? Is it to facilitate testing on the local machines? Is it somehow linked to test frequency (running one test weekly, but abridged test daily)? I am just missing the context ;)

2022-06-06 11:40 UTC, KSGulin commented
@dbogunowicz the abridged mode allows us to run a full training run, which may take hours, in minutes. This would be used for testing on commit or on nightly, when we don't want to commit to such long tests, but we still want to test the validity of our pipelines. The same can be achieved by setting args such as "max-train-samples" under the commands fields, but the benefit of the abridged mode is having one standardized definition of the arg values for a shortened run.

2022-06-06 12:03 UTC, dbogunowicz commented on tests/integrations/image_classification/args.py
> +        "negative, will run for the entire dataset",
```suggestion
        "negative, will run for the entire training set",
```

2022-06-06 12:03 UTC, dbogunowicz commented on tests/integrations/image_classification/args.py
> +        "will run for the entire dataset",
```suggestion
        "will run for the entire validation set",
```

2022-06-06 12:03 UTC, dbogunowicz commented on tests/integrations/object_detection/args.py
> +        "the entire dataset will be used, default=-1",
```suggestion
        "the entire training set will be used, default=-1",
```

2022-06-06 12:03 UTC, dbogunowicz commented on tests/integrations/object_detection/args.py
> +        "the entire dataset will be used, default=-1",
```suggestion
        "the entire validation set will be used, default=-1",
```

2022-06-14 14:10 UTC, bfineran requested changes

2022-06-14 14:10 UTC, bfineran commented on tests/integrations/transformers/test_transformers.py
> +            self.configs["train"].max_steps = 10
```suggestion
            self.configs["train"].max_train_samples = 10
```

2022-06-16 11:45 UTC, merged