blog style readme for torch sparse-quant TL notebook
neuralmagic/sparseml pull request #85
Opened 2021-02-24 22:46 UTC by bfineran

2021-02-24 22:46 UTC, bfineran commented
I'm very open to what goes in here. @reviewers please feel free to make suggestions

2021-02-24 23:38 UTC, jeanniefinks commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +[quantization](https://arxiv.org/abs/1609.07061) are well established methods for accelerating
```suggestion
[quantization](https://arxiv.org/abs/1609.07061) are well-established methods for accelerating
```

2021-02-24 23:38 UTC, jeanniefinks commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +option for real time model inference.
```suggestion
option for real-time model inference.
```

2021-02-24 23:48 UTC, jeanniefinks commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +Sparse-quantized transfer learning takes place in two phases:
```suggestion
Transfer learning is an ML approach where a model developed for solving for one task is reused and applied to another related but different task. Sparse-quantized transfer learning takes place in two phases:
```

2021-02-24 23:48 UTC, jeanniefinks commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +is a jupyter notebook that provides a step-by-step walk-through for
```suggestion
is a Jupyter Notebook that provides a step-by-step walk-through for
```

2021-02-25 01:58 UTC, jeanniefinks submitted a review, later dismissed
Great refinement on transfer learning def!

2021-02-25 14:55 UTC, markurtz requested changes

2021-02-25 14:55 UTC, markurtz commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +Sparse-quantized models leverage both techniques and can achieve speedups upwards of 6-7x when using
can we get a link out for the 6-7x to the resnet50 blog? Also, can we change to just 7x or ~7x?

2021-02-25 14:55 UTC, markurtz commented on examples/pytorch_sparse_quantized_transfer_learning/README.md
> +
grounding this with a product flow image would work well I think as discussed in slack, adding the file to this comment for the diagram as discussed

[flow-sparsification-model_sparsezoo-recipe_sparsezoo-sparsifcation_sparseml_training-deployment_deepsparse.svg.zip](https://github.com/neuralmagic/sparseml/files/6043774/flow-sparsification-model_sparsezoo-recipe_sparsezoo-sparsifcation_sparseml_training-deployment_deepsparse.svg.zip)

2021-02-25 16:15 UTC, jeanniefinks submitted a review, later dismissed

2021-02-25 16:39 UTC, markurtz approved these changes

2021-02-25 16:43 UTC, mgoin approved these changes

2021-02-25 16:44 UTC, merged