Created base class for knowledge distillation
neuralmagic/sparseml pull request #854
Opened 2022-06-08 02:33 UTC by anmarques

This PR creates a base class for knowledge distillation modifiers and changes the existing knowledge distillation modifier to inherit from the base class. The goal of this change is to enable other forms of knowledge distillation by simply implementing specialized instances of distillation losses.

2022-06-13 12:06 UTC, KSGulin approved these changes
LGTM!

2022-06-14 16:00 UTC, natuan requested changes

2022-09-13 17:51 UTC, KSGulin approved these changes

2022-09-13 17:57 UTC, natuan approved these changes

2022-09-13 17:58 UTC, merged