Rm: blog link, 7x
neuralmagic/sparseml pull request #88
Opened 2021-02-25 19:52 UTC by jeanniefinks

Temporarily removing references to 7x and blog. Will return after it's live.

2021-02-25 21:31 UTC, bfineran requested changes
There's a reference to "over 6.5x" on line 63 of the TL README

2021-02-26 01:20 UTC, NMsasa approved these changes

2021-02-26 01:21 UTC, NMsasa approved these changes

2021-02-26 01:21 UTC, NMsasa approved these changes

2021-02-26 01:22 UTC, NMsasa submitted a review, later dismissed

2021-02-26 14:14 UTC, bfineran approved these changes

2021-02-26 14:48 UTC, NMsasa approved these changes

2021-02-26 15:15 UTC, merged