added my github username to the maintainers list
neuralmagic/sparseml pull request #956
Opened 2022-07-25 17:29 UTC by Chibukach

2022-08-03 13:20 UTC, tdg5 approved these changes

2022-08-03 13:40 UTC, kazukageorge approved these changes

2022-08-03 13:43 UTC, bfineran requested changes
quick request. - let's get the username in a `#` comment in the file so you won't be added to the review selector

2022-08-04 15:45 UTC, tdg5 approved these changes

2022-08-04 16:05 UTC, bfineran approved these changes

2022-10-13 15:04 UTC, bfineran approved these changes

2022-10-13 15:05 UTC, merged