Remove confusing flag name in docstrings for transformers export.
neuralmagic/sparseml pull request #993
Opened 2022-08-16 11:55 UTC by dbogunowicz

2022-08-16 14:17 UTC, KSGulin requested changes
Good call, this flag has multiple layers of confusion. Can we also make the following changes to make it more straightforward:

L264: set action to "set_true"
L301: `convert_qat=(not no_convert_qat)`

2022-08-17 11:04 UTC, anmarques approved these changes
Thanks for cleaning it up

2022-08-17 11:08 UTC, rahul-tuli approved these changes

2022-08-17 11:11 UTC, KSGulin approved these changes

2022-08-17 13:46 UTC, bfineran approved these changes

2022-08-17 13:46 UTC, merged